/*Copyright (c) 2020-2021 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.loancorpv2.loancorpv2.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.wavemaker.commons.json.serializer.ByteArrayToStringSerializer;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetKycImageResponse implements Serializable {


    @ColumnAlias("id")
    private Long id;

    @JsonSerialize(using = ByteArrayToStringSerializer.class)
    @JsonProperty(access = Access.READ_ONLY)
    @ColumnAlias("kyc_image")
    private byte[] kycImage;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public byte[] getKycImage() {
        return this.kycImage;
    }

    public void setKycImage(byte[] kycImage) {
        this.kycImage = kycImage;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetKycImageResponse)) return false;
        final GetKycImageResponse getKycImageResponse = (GetKycImageResponse) o;
        return Objects.equals(getId(), getKycImageResponse.getId()) &&
                Objects.equals(getKycImage(), getKycImageResponse.getKycImage());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getKycImage());
    }
}
