/*Copyright (c) 2020-2021 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.loancorpv2.loancorpv2.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class TestCustomerDetailsResponse implements Serializable {


    @ColumnAlias("fname")
    private String fname;

    @ColumnAlias("lname")
    private String lname;

    @ColumnAlias("email")
    private String email;

    @ColumnAlias("dob")
    private Date dob;

    public String getFname() {
        return this.fname;
    }

    public void setFname(String fname) {
        this.fname = fname;
    }

    public String getLname() {
        return this.lname;
    }

    public void setLname(String lname) {
        this.lname = lname;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Date getDob() {
        return this.dob;
    }

    public void setDob(Date dob) {
        this.dob = dob;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TestCustomerDetailsResponse)) return false;
        final TestCustomerDetailsResponse testCustomerDetailsResponse = (TestCustomerDetailsResponse) o;
        return Objects.equals(getFname(), testCustomerDetailsResponse.getFname()) &&
                Objects.equals(getLname(), testCustomerDetailsResponse.getLname()) &&
                Objects.equals(getEmail(), testCustomerDetailsResponse.getEmail()) &&
                Objects.equals(getDob(), testCustomerDetailsResponse.getDob());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getFname(),
                getLname(),
                getEmail(),
                getDob());
    }
}
