/*Copyright (c) 2020-2021 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.loancorpv2.loancorpv2.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class UpdateLoanApplicationStatusRequest implements Serializable {


    @JsonProperty("status")
    @NotNull
    private String status;

    @JsonProperty("loanId")
    @NotNull
    private String loanId;

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getLoanId() {
        return this.loanId;
    }

    public void setLoanId(String loanId) {
        this.loanId = loanId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UpdateLoanApplicationStatusRequest)) return false;
        final UpdateLoanApplicationStatusRequest updateLoanApplicationStatusRequest = (UpdateLoanApplicationStatusRequest) o;
        return Objects.equals(getStatus(), updateLoanApplicationStatusRequest.getStatus()) &&
                Objects.equals(getLoanId(), updateLoanApplicationStatusRequest.getLoanId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getStatus(),
                getLoanId());
    }
}
