/*Copyright (c) 2020-2021 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.loancorpv2.loancorpv2.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ValidateUserResponse implements Serializable {


    @ColumnAlias("id")
    private Long id;

    @ColumnAlias("create_time")
    private Timestamp createTime;

    @ColumnAlias("last_login")
    private Timestamp lastLogin;

    @ColumnAlias("password")
    private String password;

    @ColumnAlias("role")
    private String role;

    @ColumnAlias("status")
    private String status;

    @ColumnAlias("user_id")
    private String userId;

    @ColumnAlias("customer_id")
    private Long customerId;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getLastLogin() {
        return this.lastLogin;
    }

    public void setLastLogin(Timestamp lastLogin) {
        this.lastLogin = lastLogin;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public Long getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ValidateUserResponse)) return false;
        final ValidateUserResponse validateUserResponse = (ValidateUserResponse) o;
        return Objects.equals(getId(), validateUserResponse.getId()) &&
                Objects.equals(getCreateTime(), validateUserResponse.getCreateTime()) &&
                Objects.equals(getLastLogin(), validateUserResponse.getLastLogin()) &&
                Objects.equals(getPassword(), validateUserResponse.getPassword()) &&
                Objects.equals(getRole(), validateUserResponse.getRole()) &&
                Objects.equals(getStatus(), validateUserResponse.getStatus()) &&
                Objects.equals(getUserId(), validateUserResponse.getUserId()) &&
                Objects.equals(getCustomerId(), validateUserResponse.getCustomerId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getCreateTime(),
                getLastLogin(),
                getPassword(),
                getRole(),
                getStatus(),
                getUserId(),
                getCustomerId());
    }
}
