/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.loancorpv2.googleapis.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.wavemaker.loancorpv2.googleapis.model.ResponseAddressComponentsEntryItem;
import com.wavemaker.loancorpv2.googleapis.model.ResponseGeometry;
import java.util.ArrayList;
import java.util.List;
/**
 * ResponseResultsEntryItem
 */

public class ResponseResultsEntryItem {
  @JsonProperty("formatted_address")
  private String formatted_address = null;

  @JsonProperty("types")
  private List<String> types = new ArrayList<>();

  @JsonProperty("geometry")
  private ResponseGeometry geometry = null;

  @JsonProperty("address_components")
  private List<ResponseAddressComponentsEntryItem> address_components = new ArrayList<>();

  @JsonProperty("place_id")
  private String place_id = null;

  public ResponseResultsEntryItem formatted_address(String formatted_address) {
    this.formatted_address = formatted_address;
    return this;
  }

   /**
   * Get formatted_address
   * @return formatted_address
  **/
  public String getFormattedAddress() {
    return formatted_address;
  }

  public void setFormattedAddress(String formatted_address) {
    this.formatted_address = formatted_address;
  }

  public ResponseResultsEntryItem types(List<String> types) {
    this.types = types;
    return this;
  }

  public ResponseResultsEntryItem addTypesItem(String typesItem) {
    this.types.add(typesItem);
    return this;
  }

   /**
   * Get types
   * @return types
  **/
  public List<String> getTypes() {
    return types;
  }

  public void setTypes(List<String> types) {
    this.types = types;
  }

  public ResponseResultsEntryItem geometry(ResponseGeometry geometry) {
    this.geometry = geometry;
    return this;
  }

   /**
   * Get geometry
   * @return geometry
  **/
  public ResponseGeometry getGeometry() {
    return geometry;
  }

  public void setGeometry(ResponseGeometry geometry) {
    this.geometry = geometry;
  }

  public ResponseResultsEntryItem address_components(List<ResponseAddressComponentsEntryItem> address_components) {
    this.address_components = address_components;
    return this;
  }

  public ResponseResultsEntryItem addAddressComponentsItem(ResponseAddressComponentsEntryItem address_componentsItem) {
    this.address_components.add(address_componentsItem);
    return this;
  }

   /**
   * Get address_components
   * @return address_components
  **/
  public List<ResponseAddressComponentsEntryItem> getAddressComponents() {
    return address_components;
  }

  public void setAddressComponents(List<ResponseAddressComponentsEntryItem> address_components) {
    this.address_components = address_components;
  }

  public ResponseResultsEntryItem place_id(String place_id) {
    this.place_id = place_id;
    return this;
  }

   /**
   * Get place_id
   * @return place_id
  **/
  public String getPlaceId() {
    return place_id;
  }

  public void setPlaceId(String place_id) {
    this.place_id = place_id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseResultsEntryItem Response_resultsEntryItem = (ResponseResultsEntryItem) o;
    return Objects.equals(this.formatted_address, Response_resultsEntryItem.formatted_address) &&
        Objects.equals(this.types, Response_resultsEntryItem.types) &&
        Objects.equals(this.geometry, Response_resultsEntryItem.geometry) &&
        Objects.equals(this.address_components, Response_resultsEntryItem.address_components) &&
        Objects.equals(this.place_id, Response_resultsEntryItem.place_id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(formatted_address, types, geometry, address_components, place_id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseResultsEntryItem {\n");
    
    sb.append("    formatted_address: ").append(toIndentedString(formatted_address)).append("\n");
    sb.append("    types: ").append(toIndentedString(types)).append("\n");
    sb.append("    geometry: ").append(toIndentedString(geometry)).append("\n");
    sb.append("    address_components: ").append(toIndentedString(address_components)).append("\n");
    sb.append("    place_id: ").append(toIndentedString(place_id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
