/*Copyright (c) 2020-2021 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.loancorpv2.loancorpv2.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.IOException;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Lazy;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ObjectReader;
import com.wavemaker.commons.InvalidInputException;
import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.annotations.EntityService;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.loancorpv2.loancorpv2.DocExtractedData;
import com.wavemaker.loancorpv2.loancorpv2.Document;


/**
 * ServiceImpl object for domain model class Document.
 *
 * @see Document
 */
@Service("loancorpv2.DocumentService")
@Validated
@EntityService(entityClass = Document.class, serviceId = "loancorpv2")
public class DocumentServiceImpl implements DocumentService {

    private static final Logger LOGGER = LoggerFactory.getLogger(DocumentServiceImpl.class);

    @Lazy
    @Autowired
    @Qualifier("loancorpv2.DocExtractedDataService")
    private DocExtractedDataService docExtractedDataService;

    @Autowired
    @Qualifier("loancorpv2.DocumentDao")
    private WMGenericDao<Document, Integer> wmGenericDao;

    @Autowired
    @Qualifier("wmAppObjectMapper")
    private ObjectMapper objectMapper;


    public void setWMGenericDao(WMGenericDao<Document, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "loancorpv2TransactionManager")
    @Override
    public Document create(Document document) {
        LOGGER.debug("Creating a new Document with information: {}", document);

        Document documentCreated = this.wmGenericDao.create(document);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(documentCreated);
    }

    @Transactional(readOnly = true, value = "loancorpv2TransactionManager")
    @Override
    public Document getById(Integer documentId) {
        LOGGER.debug("Finding Document by id: {}", documentId);
        return this.wmGenericDao.findById(documentId);
    }

    @Transactional(readOnly = true, value = "loancorpv2TransactionManager")
    @Override
    public Document findById(Integer documentId) {
        LOGGER.debug("Finding Document by id: {}", documentId);
        try {
            return this.wmGenericDao.findById(documentId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No Document found with id: {}", documentId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "loancorpv2TransactionManager")
    @Override
    public List<Document> findByMultipleIds(List<Integer> documentIds, boolean orderedReturn) {
        LOGGER.debug("Finding Documents by ids: {}", documentIds);

        return this.wmGenericDao.findByMultipleIds(documentIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "loancorpv2TransactionManager")
    @Override
    public Document update(Document document) {
        LOGGER.debug("Updating Document with information: {}", document);

        this.wmGenericDao.update(document);
        this.wmGenericDao.refresh(document);

        return document;
    }

    @Transactional(value = "loancorpv2TransactionManager")
    @Override
    public Document partialUpdate(Integer documentId, Map<String, Object>documentPatch) {
        LOGGER.debug("Partially Updating the Document with id: {}", documentId);

        Document document = getById(documentId);

        try {
            ObjectReader documentReader = this.objectMapper.reader().forType(Document.class).withValueToUpdate(document);
            document = documentReader.readValue(this.objectMapper.writeValueAsString(documentPatch));
        } catch (IOException ex) {
            LOGGER.debug("There was a problem in applying the patch: {}", documentPatch, ex);
            throw new InvalidInputException("Could not apply patch",ex);
        }

        document = update(document);

        return document;
    }

    @Transactional(value = "loancorpv2TransactionManager")
    @Override
    public Document delete(Integer documentId) {
        LOGGER.debug("Deleting Document with id: {}", documentId);
        Document deleted = this.wmGenericDao.findById(documentId);
        if (deleted == null) {
            LOGGER.debug("No Document found with id: {}", documentId);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), Document.class.getSimpleName(), documentId);
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "loancorpv2TransactionManager")
    @Override
    public void delete(Document document) {
        LOGGER.debug("Deleting Document with {}", document);
        this.wmGenericDao.delete(document);
    }

    @Transactional(readOnly = true, value = "loancorpv2TransactionManager")
    @Override
    public Page<Document> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Documents");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "loancorpv2TransactionManager")
    @Override
    public Page<Document> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Documents");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "loancorpv2TransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service loancorpv2 for table Document to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "loancorpv2TransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service loancorpv2 for table Document to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "loancorpv2TransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "loancorpv2TransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "loancorpv2TransactionManager")
    @Override
    public Page<DocExtractedData> findAssociatedDocExtractedDatas(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated docExtractedDatas");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("document.id = '" + id + "'");

        return docExtractedDataService.findAll(queryBuilder.toString(), pageable);
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service DocExtractedDataService instance
     */
    protected void setDocExtractedDataService(DocExtractedDataService service) {
        this.docExtractedDataService = service;
    }

}
