/*Copyright (c) 2020-2021 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.loancorpv2.loancorpv2;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * CommTrail generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`comm_trail`")
public class CommTrail implements Serializable {

    private Integer id;
    private Integer loanApplicationId;
    private String commType;
    private String commDesc;
    private Timestamp createtime;
    private String triggeredBy;
    private LoanApplication loanApplication;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`loan_application_id`", nullable = true, scale = 0, precision = 10)
    public Integer getLoanApplicationId() {
        return this.loanApplicationId;
    }

    public void setLoanApplicationId(Integer loanApplicationId) {
        this.loanApplicationId = loanApplicationId;
    }

    @Column(name = "`comm_type`", nullable = true, length = 255)
    public String getCommType() {
        return this.commType;
    }

    public void setCommType(String commType) {
        this.commType = commType;
    }

    @Column(name = "`comm_desc`", nullable = true, length = 2147483647)
    public String getCommDesc() {
        return this.commDesc;
    }

    public void setCommDesc(String commDesc) {
        this.commDesc = commDesc;
    }

    @Column(name = "`createtime`", nullable = true)
    public Timestamp getCreatetime() {
        return this.createtime;
    }

    public void setCreatetime(Timestamp createtime) {
        this.createtime = createtime;
    }

    @Column(name = "`triggered_by`", nullable = true, length = 255)
    public String getTriggeredBy() {
        return this.triggeredBy;
    }

    public void setTriggeredBy(String triggeredBy) {
        this.triggeredBy = triggeredBy;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`loan_application_id`", referencedColumnName = "`id`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_comm_trail_TO_loan_apYGnUg`"))
    @Fetch(FetchMode.JOIN)
    public LoanApplication getLoanApplication() {
        return this.loanApplication;
    }

    public void setLoanApplication(LoanApplication loanApplication) {
        if(loanApplication != null) {
            this.loanApplicationId = loanApplication.getId();
        }

        this.loanApplication = loanApplication;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CommTrail)) return false;
        final CommTrail commTrail = (CommTrail) o;
        return Objects.equals(getId(), commTrail.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}
