/*Copyright (c) 2020-2021 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.loancorpv2.loancorpv2;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * CreditDetails generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`credit_details`")
public class CreditDetails implements Serializable {

    private Integer id;
    private Integer creditHistoryId;
    private String creditType;
    private Integer creditAmt;
    private Integer creditLimit;
    private String ssnNo;
    private CreditHistory creditHistory;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`credit_history_id`", nullable = true, scale = 0, precision = 10)
    public Integer getCreditHistoryId() {
        return this.creditHistoryId;
    }

    public void setCreditHistoryId(Integer creditHistoryId) {
        this.creditHistoryId = creditHistoryId;
    }

    @Column(name = "`credit_type`", nullable = true, length = 255)
    public String getCreditType() {
        return this.creditType;
    }

    public void setCreditType(String creditType) {
        this.creditType = creditType;
    }

    @Column(name = "`credit_amt`", nullable = true, scale = 0, precision = 10)
    public Integer getCreditAmt() {
        return this.creditAmt;
    }

    public void setCreditAmt(Integer creditAmt) {
        this.creditAmt = creditAmt;
    }

    @Column(name = "`credit_limit`", nullable = true, scale = 0, precision = 10)
    public Integer getCreditLimit() {
        return this.creditLimit;
    }

    public void setCreditLimit(Integer creditLimit) {
        this.creditLimit = creditLimit;
    }

    @Column(name = "`ssn_no`", nullable = true, length = 255)
    public String getSsnNo() {
        return this.ssnNo;
    }

    public void setSsnNo(String ssnNo) {
        this.ssnNo = ssnNo;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`credit_history_id`", referencedColumnName = "`id`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_credit_details_TO_creeeJu6`"))
    @Fetch(FetchMode.JOIN)
    public CreditHistory getCreditHistory() {
        return this.creditHistory;
    }

    public void setCreditHistory(CreditHistory creditHistory) {
        if(creditHistory != null) {
            this.creditHistoryId = creditHistory.getId();
        }

        this.creditHistory = creditHistory;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CreditDetails)) return false;
        final CreditDetails creditDetails = (CreditDetails) o;
        return Objects.equals(getId(), creditDetails.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}
