/*Copyright (c) 2020-2021 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.loancorpv2.loancorpv2;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * DocExtractedData generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`doc_extracted_data`")
public class DocExtractedData implements Serializable {

    private Integer id;
    private Integer documentId;
    private String w2EinNo;
    private Integer w2Wages;
    private String w2State;
    private String w2Zip;
    private String w2Address;
    private String w2SsnNo;
    private String dlNo;
    private String docType;
    private String paNo;
    private Date paIssueDate;
    private Date paExpiryDate;
    private Document document;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`document_id`", nullable = true, scale = 0, precision = 10)
    public Integer getDocumentId() {
        return this.documentId;
    }

    public void setDocumentId(Integer documentId) {
        this.documentId = documentId;
    }

    @Column(name = "`w2_ein_no`", nullable = true, length = 255)
    public String getW2EinNo() {
        return this.w2EinNo;
    }

    public void setW2EinNo(String w2EinNo) {
        this.w2EinNo = w2EinNo;
    }

    @Column(name = "`w2_wages`", nullable = true, scale = 0, precision = 10)
    public Integer getW2Wages() {
        return this.w2Wages;
    }

    public void setW2Wages(Integer w2Wages) {
        this.w2Wages = w2Wages;
    }

    @Column(name = "`w2_state`", nullable = true, length = 255)
    public String getW2State() {
        return this.w2State;
    }

    public void setW2State(String w2State) {
        this.w2State = w2State;
    }

    @Column(name = "`w2_zip`", nullable = true, length = 255)
    public String getW2Zip() {
        return this.w2Zip;
    }

    public void setW2Zip(String w2Zip) {
        this.w2Zip = w2Zip;
    }

    @Column(name = "`w2_address`", nullable = true, length = 255)
    public String getW2Address() {
        return this.w2Address;
    }

    public void setW2Address(String w2Address) {
        this.w2Address = w2Address;
    }

    @Column(name = "`w2_ssn_no`", nullable = true, length = 255)
    public String getW2SsnNo() {
        return this.w2SsnNo;
    }

    public void setW2SsnNo(String w2SsnNo) {
        this.w2SsnNo = w2SsnNo;
    }

    @Column(name = "`dl_no`", nullable = true, length = 255)
    public String getDlNo() {
        return this.dlNo;
    }

    public void setDlNo(String dlNo) {
        this.dlNo = dlNo;
    }

    @Column(name = "`doc_type`", nullable = true, length = 255)
    public String getDocType() {
        return this.docType;
    }

    public void setDocType(String docType) {
        this.docType = docType;
    }

    @Column(name = "`pa_no`", nullable = true, length = 255)
    public String getPaNo() {
        return this.paNo;
    }

    public void setPaNo(String paNo) {
        this.paNo = paNo;
    }

    @Column(name = "`pa_issue_date`", nullable = true)
    public Date getPaIssueDate() {
        return this.paIssueDate;
    }

    public void setPaIssueDate(Date paIssueDate) {
        this.paIssueDate = paIssueDate;
    }

    @Column(name = "`pa_expiry_date`", nullable = true)
    public Date getPaExpiryDate() {
        return this.paExpiryDate;
    }

    public void setPaExpiryDate(Date paExpiryDate) {
        this.paExpiryDate = paExpiryDate;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`document_id`", referencedColumnName = "`id`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_doc_extracted_data_TOR7rmU`"))
    @Fetch(FetchMode.JOIN)
    public Document getDocument() {
        return this.document;
    }

    public void setDocument(Document document) {
        if(document != null) {
            this.documentId = document.getId();
        }

        this.document = document;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof DocExtractedData)) return false;
        final DocExtractedData docExtractedData = (DocExtractedData) o;
        return Objects.equals(getId(), docExtractedData.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}
