/*Copyright (c) 2020-2021 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.loancorpv2.loancorpv2;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LoanDetails generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`loan_details`")
public class LoanDetails implements Serializable {

    private Integer id;
    private Integer amount;
    private Integer defaultProbability;
    private String emiFreq;
    private Integer interestAmt;
    private Integer interestRate;
    private Integer tenure;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`amount`", nullable = true, scale = 0, precision = 10)
    public Integer getAmount() {
        return this.amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    @Column(name = "`default_probability`", nullable = true, scale = 0, precision = 10)
    public Integer getDefaultProbability() {
        return this.defaultProbability;
    }

    public void setDefaultProbability(Integer defaultProbability) {
        this.defaultProbability = defaultProbability;
    }

    @Column(name = "`emi_freq`", nullable = true, length = 255)
    public String getEmiFreq() {
        return this.emiFreq;
    }

    public void setEmiFreq(String emiFreq) {
        this.emiFreq = emiFreq;
    }

    @Column(name = "`interest_amt`", nullable = true, scale = 0, precision = 10)
    public Integer getInterestAmt() {
        return this.interestAmt;
    }

    public void setInterestAmt(Integer interestAmt) {
        this.interestAmt = interestAmt;
    }

    @Column(name = "`interest_rate`", nullable = true, scale = 0, precision = 10)
    public Integer getInterestRate() {
        return this.interestRate;
    }

    public void setInterestRate(Integer interestRate) {
        this.interestRate = interestRate;
    }

    @Column(name = "`tenure`", nullable = true, scale = 0, precision = 10)
    public Integer getTenure() {
        return this.tenure;
    }

    public void setTenure(Integer tenure) {
        this.tenure = tenure;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof LoanDetails)) return false;
        final LoanDetails loanDetails = (LoanDetails) o;
        return Objects.equals(getId(), loanDetails.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}
